### PR TITLE
Fix paths in readme

### PR DESCRIPTION
**Pull request by simcop2387**
## Description
Fixes the paths in the README.md

## How to test
No testing needed

## Contributor license agreement signed?
I have not signed a CLA yet.  However I believe this change does not meet the requirements needed for it to be considered copyrightable in any jurisdiction and make no such claims about it.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Simcop, thanks for helping improve the documentation.

You are completely right about it not being a copyrightable change, however we have a blanket rule requiring the CLA. Because we have hundreds of unique contributors to our repositories, this simplifies our legal management considerably. It also avoids debates on PR's that are closer to the grey area.

If you don't want to sign the CLA and just want to get this updated I can get it fixed up. Otherwise you can kick off the signing process at https://mycroft.ai/cla/

**Comment by simcop2387** [comment]
No objections to the CLA, just hoped to avoid any red tape/bureaucracy for a simple change.  I've kicked off the cla now

**Comment by krisgesling** [comment]
Yeah understandable. The upside is that you will be added to our [list of excellent humans](github.com/mycroftAI/contributors) :)

Have shot it through, let me know if you have any questions.

**Comment by simcop2387** [comment]
All signed

**Comment by krisgesling** [comment]
Thanks! Merging

**Pull request merged**
