### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hammyMarc**
For some reason, a fresh install of Unbuntu 18 and python3.7 didn't include pip. Added a line to ensure people have pip, before proceeding.

## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by hammyMarc** [comment]
I think I have other updates, too. These instructions are not sufficiently complete and I had to do some actions that, if I weren't familiar with Linux, would have been entirely opaque.

**Comment by krisgesling** [comment]
Hey, I wonder if this was meant to be included up at line 48:
> * Use the package management system to install Python 3.7, Python 3 pip and PostgreSQL 10
> ```
> sudo apt-get install postgresql python3.7 python
> ```

This should probably be:
> ```
> sudo apt-get install postgresql python3.7 python3-pip
> ```

**Comment by hammyMarc** [comment]
@krisgesling good add. Let's go with that.

**Comment by hammyMarc** [comment]
@krisgesling getting an error when trying to install the scripts. I ran a manual install, to ensure that markdown was installed... but still getting the error. Thoughts? Another opportunity to improve README?

**Comment by chrisveilleux** [comment]
There is a large update to this repository that is currently running in the test environment.  It includes improvements to the database bootstrap script, making it more user-friendly.

Also, please check out the Contributor Licensing Agreement.  PR's won't be merged unless you have accepted the agreement.  Thanks!

**Comment by hammyMarc** [comment]
@chrisveilleux good to know. Thanks. I will check. Just putting my shoulder to the wheel, so to speak.

**Comment by krisgesling** [comment]
Just to save you the searching: https://mycroft.ai/cla/

**Comment by hammyMarc** [comment]
Your kind. Thank you. I have completed the initial submission. Cheers.

**Comment by hammyMarc** [comment]
@krisgesling and @chrisveilleux, if you guys want me to QA the new install README.md for the next release, let me know. I will build a new image of whatever Ubuntu version is supported... and give it a whirl.

-Marc

**Review by chrisveilleux — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
