### PR TITLE
Add post processing to Jenkins to clean up Docker containers and images.

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description
Cleans up Docker images after the CI process completes successfully.  Images will remain if the CI process fails for troubleshooting purposes.  Assumption is that if the build is successful, the docker images will no longer be needed.

## How to test
This PR passes its CI requirement and there are no lingering images on the Docker host.

## Contributor license agreement signed?
CLA [Y]

### CODE REVIEW

**Comment by krisgesling** [comment]
This seems right, have you replayed a job with it?

**Comment by chrisveilleux** [comment]
Yes.  Replayed jobs works.

**Comment by krisgesling** [comment]
Hey I was just looking at this for the other repo's and thought
`${env.BUILD_TAG}` => `"jenkins-mycroft-skills-PR-1418-13"`
 would be a safer label than:
`${BRANCH_ALIAS}` => `"PR-1418"`

**Comment by chrisveilleux** [comment]
> Hey I was just looking at this for the other repo's and thought
> `${env.BUILD_TAG}` => `"jenkins-mycroft-skills-PR-1418-13"`
> would be a safer label than:
> `${BRANCH_ALIAS}` => `"PR-1418"`

What is your rationale?

**Comment by ken-mycroft** [comment]
Seems reasonable.

Ken Smith
Mycroft AI <http://www.mycroft.ai/> | Senior Developer| 954-895-2816
300 E 39th St #20, Kansas City, MO 64111

**Comment by krisgesling** [comment]
If we tag only by PR number then we could end up with multiple jobs on the same host with the same label from different repo's.

It's fairly unlikely at the moment, but it becomes more likely the more of our projects that do it. 

`${BUILD_TAG}` seems truly unique given it has the repo, PR, and build number.

**Comment by chrisveilleux** [comment]
@krisgesling Pushed a change to use the job name instead of the branch name as we discussed.

**Review by krisgesling — APPROVED** [review]

**Pull request merged**
